25 change proxies to meta service
GolosChain/facade-service pull request #26
Opened 2018-12-26 09:18 UTC by Bacher

2018-12-26 10:03 UTC, IvanBlacky requested changes

2018-12-26 10:03 UTC, IvanBlacky commented on package.json
> +  "version": "1.0.0",
Должно было поменяться

2018-12-26 10:40 UTC, Format-X22 requested changes
Новых не добавлю, как будет пофикшены найденные - апрув.

2018-12-26 15:55 UTC, IvanBlacky approved these changes

2018-12-28 09:44 UTC, Format-X22 approved these changes

2018-12-28 16:37 UTC, merged