27 Refactor: use new core lib version
GolosChain/facade-service pull request #32
Opened 2019-01-14 10:37 UTC by IvanBlacky

2019-01-25 09:41 UTC, Format-X22 requested changes

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Content.js
> +        return await this.callService('prism', 'getNaturalFeed', data);
Мелочь, но мы отделяем блок кода с объявлением переменных от вычислений и от ретурнов, где это применимо. Тут применимо.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Content.js
> +        return await this.callService('prism', 'getPopularFeed', data);
Мелочь, но мы отделяем блок кода с объявлением переменных от вычислений и от ретурнов, где это применимо. Тут применимо.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Content.js
> +        return await this.callService('prism', 'getActualFeed', data);
Мелочь, но мы отделяем блок кода с объявлением переменных от вычислений и от ретурнов, где это применимо. Тут применимо.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Content.js
> +        return await this.callService('prism', 'getPromoFeed', data);
Мелочь, но мы отделяем блок кода с объявлением переменных от вычислений и от ретурнов, где это применимо. Тут применимо.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Content.js
> +        return await this.callService('prism', 'getPersonalFeed', data);
Мелочь, но мы отделяем блок кода с объявлением переменных от вычислений и от ретурнов, где это применимо. Тут применимо.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Content.js
> +        return await this.callService('prism', 'getPersonalFeed', data);
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/History.js
> +class History extends Basic {
Пропуска строки не хватает.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/History.js
> +        return await this.callService('notify', 'history', data);
Мелочь, но мы отделяем блок кода с объявлением переменных от вычислений и от ретурнов, где это применимо. Тут применимо.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/History.js
> +        return await this.callService('onlineNotify', 'history', data);
Мелочь, но мы отделяем блок кода с объявлением переменных от вычислений и от ретурнов, где это применимо. Тут применимо.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/History.js
> +        return await this.callService('push', 'history', data);
Мелочь, но мы отделяем блок кода с объявлением переменных от вычислений и от ретурнов, где это применимо. Тут применимо.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Meta.js
> +class Meta extends Basic {
Пропуск строки бы.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +class Options extends Basic {
Пропуск строки бы.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Rates.js
> +class Rates extends Basic {
Пропуск строки бы.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Registration.js
> +class Registration extends Basic {
Пропуск строки бы.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Subscribe.js
> +class Subscribe extends Basic {
Пропуск строки бы.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Subscribe.js
> +        return await this.callService('onlineNotify', 'subscribe', data);
Мелочь, но мы отделяем блок кода с объявлением переменных от вычислений и от ретурнов, где это применимо. Тут применимо.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Subscribe.js
> +        return await this.callService('onlineNotify', 'unsubscribe', data);
Мелочь, но мы отделяем блок кода с объявлением переменных от вычислений и от ретурнов, где это применимо. Тут применимо.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Subscribe.js
> +        return await this.callService('push', 'notifyOn', data);
Мелочь, но мы отделяем блок кода с объявлением переменных от вычислений и от ретурнов, где это применимо. Тут применимо.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Subscribe.js
> +        return await this.callService('push', 'notifyOff', data);
Мелочь, но мы отделяем блок кода с объявлением переменных от вычислений и от ретурнов, где это применимо. Тут применимо.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Transfer.js
> +class Transfer extends Basic {
Пропуск строки бы.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/History.js
> +        return await this.callService('notify', 'history', data);
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/History.js
> +        return await this.callService('notify', 'historyFresh', { user });
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/History.js
> +        return await this.callService('onlineNotify', 'history', data);
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/History.js
> +        return await this.callService('onlineNotify', 'historyFresh', { user });
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/History.js
> +        return await this.callService('push', 'history', data);
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/History.js
> +        return await this.callService('push', 'historyFresh', { user, profile });
Нужно в итоге решить - делаем переменную с данными или параметры сразу в запрос пробрасываем - а то там так, в другом месте сяк... вероятно стоит выбрать компактный вариант как тут и везде переместить переменную data сразу в аргумент вызова.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/History.js
> +        return await this.callService('push', 'historyFresh', { user, profile });
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/History.js
> +        return await this.callService('notify', 'markAsViewed', { user, ids });
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/History.js
> +        return await this.callService('notify', 'markAllAsViewed', { user });
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Offline.js
> +class Offline extends Basic {
Пропуск строки бы.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +        const response = await this.callService('options', 'getFavorites', { user });
Ниже идет обработка ошибки, её нужно убрать - callService сделает всё сам.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +        const response = await this.callService('options', 'addFavorite', { user, permlink });
Ниже идет обработка ошибки, её нужно убрать - callService сделает всё сам.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +        const response = await this.callService('options', 'getFavorites', { user });
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +        const response = await this.callService('options', 'addFavorite', { user, permlink });
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +        const response = await this.callService('options', 'removeFavorite', { user, permlink });
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +        const response = await this.callService('options', 'removeFavorite', { user, permlink });
Ниже идет обработка ошибки, её нужно убрать - callService сделает всё сам.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +        const response = await this.callService('notify', 'getBlackList', { owner });
Ниже идет обработка ошибки, её нужно убрать - callService сделает всё сам.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +        const response = await this.callService('notify', 'addToBlackList', { owner, banned });
Ниже идет обработка ошибки, её нужно убрать - callService сделает всё сам.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +        const response = await this.callService('notify', 'removeFromBlackList', { owner, banned });
Ниже идет обработка ошибки, её нужно убрать - callService сделает всё сам.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +        const response = await this.callService(service, method, data);
Тут нужно подумать о применимости callService - ниже есть обработка ошибки, но она по своему делает это, вероятно стоит вернуть sendTo.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +            const { error } = await this.callService(service, method, { user, profile, data });
Тут нужно подумать о применимости callService - ниже есть обработка ошибки, но она по своему делает это, вероятно стоит вернуть sendTo.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +        const response = await this.callService('notify', 'getBlackList', { owner });
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +        const response = await this.callService('notify', 'addToBlackList', { owner, banned });
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Options.js
> +        const response = await this.callService('notify', 'removeFromBlackList', { owner, banned });
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Subscribe.js
> +        return await this.callService('onlineNotify', 'subscribe', data);
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Subscribe.js
> +        return await this.callService('onlineNotify', 'subscribe', data);
Также другие мета-данные то другие, судя по всему.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Subscribe.js
> +        return await this.callService('onlineNotify', 'unsubscribe', data);
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Subscribe.js
> +        return await this.callService('push', 'notifyOn', data);
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Subscribe.js
> +        return await this.callService('push', 'notifyOff', data);
Есть острые подозрения что работать не будет так как формат мета-данных у нас вроде как поменялся и user нужно по другому извлекать.

2019-01-25 09:41 UTC, Format-X22 commented on src/controllers/Transfer.js
> +        const response = await this.callService('frontend', 'transfer', {
Ниже есть проверка на ошибки - нужно их убрать.

2019-01-25 09:41 UTC, Format-X22 commented on src/services/Connector.js
> +            }
Нужно добавить отбивку ошибкой о запрете доступа, иначе будет пустой ответ, который будет интерпретирован как status: 'OK', что не правильно.

2019-01-25 09:41 UTC, Format-X22 commented on src/services/Connector.js
> +            if (params.auth && params.auth.user && params.auth.roles) {
Достаточно понимать что user установлен, роли проверять уже избыточно.

2019-01-25 09:43 UTC, Format-X22 reviewed
Нужно обновить документацию - формат данных приходящих ведь поменялся.

2019-01-28 10:54 UTC, IvanBlacky commented on src/controllers/History.js
> +        return await this.callService('notify', 'history', data);
`user` -- все еще свойство объекта запроса первого уровня вложенности

2019-01-28 16:49 UTC, Format-X22 reviewed
Необходимо убрать userMapping

2019-02-01 10:33 UTC, Format-X22 approved these changes

2019-02-01 10:36 UTC, bacher approved these changes

2019-02-08 09:45 UTC, merged