Cyberway
GolosChain/facade-service pull request #55
Opened 2019-03-22 10:57 UTC by Format-X22

2019-03-22 11:22 UTC, bacher requested changes

2019-03-22 11:22 UTC, Bacher commented on src/controllers/Options.js
> +        const basic = Object(
А что это за Object() ?

2019-03-22 13:39 UTC, IvanBlacky commented on src/controllers/Options.js
> +        const basic = Object(
Почему-то без этого не всегда приходил правильный ответ (не в виде правильного объекта) . Я точнее уже не помню, но надо чтобы было так

2019-03-22 14:37 UTC, Bacher commented on src/controllers/Options.js
> +        const basic = Object(
Может корректнее явно вызвать valueOf() у результата? Я так понимаю Object именно это и делает.

2019-03-22 16:56 UTC, Format-X22 commented on src/controllers/Options.js
> +            return this._makeGetError(error, errorPrefix);
А тут то баг, раньше был throw.

2019-03-25 16:59 UTC, IvanBlacky approved these changes

2019-03-25 18:22 UTC, bacher approved these changes

2019-03-26 08:49 UTC, merged