68 add meta types
GolosChain/facade-service pull request #69
Opened 2019-04-04 11:08 UTC by IvanBlacky

2019-04-04 11:09 UTC, bacher requested changes

2019-04-04 11:09 UTC, Bacher commented on README.md
> +        type <string>               // Тип профиля ('gls' либо 'cyber')
Дефолт не указан

2019-04-04 11:20 UTC, bacher requested changes

2019-04-04 11:20 UTC, Bacher commented on README.md
> +        type <string>               // Тип профиля ('gls' либо 'cyber'). По-умолчанию 'gls'
![image](https://user-images.githubusercontent.com/2598671/55551989-d229d580-56e4-11e9-941d-269c2e8ec650.png)

Олег обычно вот так в скобках указывает

2019-04-04 11:27 UTC, bacher approved these changes

2019-04-04 11:28 UTC, beautyfree commented on README.md
> +        type <string>('gls')               // Тип профиля ('gls' либо 'cyber')
Слишком много отступов!

2019-04-05 10:29 UTC, bacher approved these changes

2019-04-05 10:33 UTC, Format-X22 approved these changes

2019-04-05 10:43 UTC, merged